            - name: Deploy WordPress plugin
  # You may pin to the exact commit or the version.
  # uses: yukihiko-shinoda/action-deploy-wordpress-plugin@e9191f098013f5fb3a4df8a9503e15030e52c1a7
  uses: yukihiko-shinoda/action-deploy-wordpress-plugin@v2.1.1
  with:
    # Expect deploy version only for test mode for CI
    expect-deploy-version-for-test: # optional, default is 
    # Deploy version only for test mode for CI
    deploy-version-for-test: # optional, default is 
          
