name: Deploy to WordPress.org Repository
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SVN_USERNAME: ${{ secrets.SVN_USERNAME }}         # или WP_SVN_USERNAME
      SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}         # или WP_SVN_PASSWORD
      SLUG: bizzio-sync-for-woocommerce
      ASSETS_DIR: assets
      BUILD_DIR: bizzio-sync-for-woocommerce
      INPUT_DRY_RUN: true
      INPUT_GENERATE_ZIP: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show workspace layout
        run: |
          pwd
          ls -la
          ls -la .github || true
          ls -la .github/scripts || true

      - name: Run original deploy script
        shell: bash
        run: bash .github/scripts/deploy.sh
