# .github/workflows/plugin-check.yml
name: Plugin Code Quality Check

on:
  pull_request:
    branches:
      - main # Trigger only when PR is made *towards* main
    paths:
      - "**.php"
      - "**/plugin/**"

jobs:
  plugin-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Plugin Check
        uses: wordpress/plugin-check-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          build-dir: "./bizzio-sync-gencloud" # или ./my-plugin ако е в подпапка
          strict: true
          include-experimental: true
