name: 📊 GitHub Traffic Monitor

on:
  schedule:
    - cron: "*/30 * * * *" # Пуска се на всеки 30 минути
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Fetch GitHub Traffic Data
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          mkdir -p .traffic
          curl -s -H "Authorization: token $GH_TOKEN" https://api.github.com/repos/$REPO/traffic/clones > .traffic/clones.json
          curl -s -H "Authorization: token $GH_TOKEN" https://api.github.com/repos/$REPO/traffic/views > .traffic/views.json
          curl -s -H "Authorization: token $GH_TOKEN" https://api.github.com/repos/$REPO/releases > .traffic/releases.json

      - name: Detect Changes and Notify
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}
        run: |
          changed=0
          mkdir -p .traffic-old

          # Load previous if exists
          cp .traffic/*.json .traffic-old/ 2>/dev/null || true

          # Save current as last
          cp .traffic/*.json .traffic-old/

          # Extract current counts
          cur_clones=$(jq '.count' .traffic/clones.json)
          cur_views=$(jq '.count' .traffic/views.json)
          cur_downloads=$(jq '[.[].assets[]?.download_count] | add' .traffic/releases.json)

          # Extract old counts (or default 0)
          old_clones=$(jq '.count // 0' .traffic-old/clones.json 2>/dev/null || echo 0)
          old_views=$(jq '.count // 0' .traffic-old/views.json 2>/dev/null || echo 0)
          old_downloads=$(jq '[.[].assets[]?.download_count] | add' .traffic-old/releases.json 2>/dev/null || echo 0)

          msg=""

          if [ "$cur_clones" -gt "$old_clones" ]; then
            msg="${msg}📥 Нов clone: $((cur_clones - old_clones)) (общо: $cur_clones)\n"
            changed=1
          fi

          if [ "$cur_views" -gt "$old_views" ]; then
            msg="${msg}👁️ Нови посещения: $((cur_views - old_views)) (общо: $cur_views)\n"
            changed=1
          fi

          if [ "$cur_downloads" -gt "$old_downloads" ]; then
            msg="${msg}📦 Нови тегления на release: $((cur_downloads - old_downloads)) (общо: $cur_downloads)\n"
            changed=1
          fi

          if [ "$changed" -eq 1 ]; then
            curl -s -X POST https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage \
              -d chat_id="$TELEGRAM_CHAT" \
              -d text="📊 GitHub трафик отчет за ${{ github.repository }}:\n$msg"
          else
            echo "No new activity detected."
          fi
